// Pirate Weather Icons
// clear-day, clear-night, rain, snow, sleet, wind, fog, cloudy, partly-cloudy-day and partly-cloudy-night
// mostly-clear-day, mostly-clear-night, mostly-cloudy-day, mostly-cloudy-night, possible-rain-day, possible-rain-night
// possible-snow-day, possible-snow-night, possible-sleet-day, possible-sleet-night, possible-precipitation-day
// possible-precipitation-night, precipitation, drizzle, light-rain, heavy-rain, flurries, light-snow, heavy-snow
// very-light-sleet, light-sleet, heavy-sleet, breezy, dangerous-wind

export const cwcDaytimePirateWeatherIcons: { [key: string]: string; } = {
  freezing_rain_heavy: 'rainy-3',
  'heavy freezing rain': 'rainy-3',
  freezing_rain: 'rainy-2',
  'freezing rain': 'rainy-2',
  freezing_rain_light: 'rainy-1',
  'light freezing rain': 'rainy-1',
  freezing_drizzle: 'rain-and-sleet-mix',
  sleet: 'rain-and-sleet-mix',
  'freezing drizzle': 'rain-and-sleet-mix',
  ice_pellets_heavy: 'rain-and-snow-mix',
  'heavy ice pellets': 'rain-and-snow-mix',
  ice_pellets: 'rain-and-snow-mix',
  'ice pellets': 'rain-and-snow-mix',
  ice_pellets_light: 'rain-and-snow-mix',
  'light ice pellets': 'rain-and-snow-mix',
  snow_heavy: 'snowy-3',
  'heavy snow': 'snowy-3',
  snow: 'snowy-2',
  snow_light: 'snowy-1',
  'light snow': 'snowy-1',
  flurries: 'wind',
  tstorm: 'tropical-storm',
  rain_heavy: 'rainy-3',
  'heavy rain': 'rainy-3',
  rain_light: 'rainy-1',
  rainy: 'rainy-1',
  'light rain': 'rainy-1',
  rain: 'rainy-2',
  drizzle: 'rainy-1',
  fog_light: 'haze',
  'light fog': 'haze',
  fog: 'fog',
  cloudy: 'cloudy-original',
  mostly_cloudy: 'cloudy-day-3',
  'mostly cloudy': 'cloudy-day-3',
  partly_cloudy: 'cloudy-day-2',
  partlycloudy: 'cloudy-day-2',
  'partly-cloudy-day': 'cloudy-day-2',
  'partly cloudy': 'cloudy-day-2',
  mostly_clear: 'cloudy-day-1',
  'mostly clear': 'cloudy-day-1',
  clear: 'day',
  'clear-day': 'day',
  wind: 'wind',
  windy: 'wind',
  sunny: 'day',
  'clear-night': 'day',
};

export const cwcNightlyPirateWeaterIcons: { [key: string]: string; } = {
  ...cwcDaytimePirateWeatherIcons,
  freezing_rain_heavy: 'rainy-6',
  'heavy freezing rain': 'rainy-6',
  freezing_rain: 'rainy-5',
  'freezing rain': 'rainy-5',
  freezing_rain_light: 'rainy-4',
  'light freezing rain': 'rainy-4',
  // freezing_drizzle: 'rain-and-sleet-mix',
  // ice_pellets_heavy: 'rain-and-snow-mix',
  // ice_pellets: 'rain-and-snow-mix',
  // ice_pellets_light: 'rain-and-snow-mix',
  snow_heavy: 'snowy-6',
  'heavy snow': 'snowy-6',
  snow: 'snowy-5',
  snow_light: 'snowy-4',
  'light snow': 'snowy-4',
  // flurries: 'wind',
  // tstorm: 'tropical-storm',
  rain_heavy: 'rainy-6',
  'heavy rain': 'rainy-6',
  rain_light: 'rainy-4',
  'light rain': 'rainy-4',
  rain: 'rainy-5',
  drizzle: 'rainy-4',
  // fog_light: 'haze',
  // fog: 'fog',
  // cloudy: 'cloudy',
  mostly_cloudy: 'cloudy-night-3',
  'mostly cloudy': 'cloudy-night-3',
  partly_cloudy: 'cloudy-night-2',
  partlycloudy: 'cloudy-night-2',
  'partly-cloudy-night': 'cloudy-night-2',
  'partly cloudy': 'cloudy-night-2',
  mostly_clear: 'cloudy-night-1',
  'mostly clear': 'cloudy-night-1',
  clear: 'night',
  'clear-night': 'night',
  sunny: 'night',
};
