
export const cwcClimacellDayIcons: { [key: string]: string; } = {
  freezing_rain_heavy: "rainy-3",
  freezing_rain: "rainy-2",
  freezing_rain_light: "rainy-1",
  freezing_drizzle: "rain-and-sleet-mix",
  ice_pellets_heavy: "rain-and-snow-mix",
  ice_pellets: "rain-and-snow-mix",
  ice_pellets_light: "rain-and-snow-mix",
  snow_heavy: "snowy-3",
  snow: "snowy-2",
  snow_light: "snowy-1",
  flurries: "wind",
  tstorm: "tropical-storm",
  rain_heavy: "rainy-3",
  rain_light: "rainy-1",
  rain: "rainy-2",
  drizzle: "rainy-1",
  fog_light: "haze",
  fog: "fog",
  cloudy: "cloudy-original",
  mostly_cloudy: "cloudy-day-3",
  partly_cloudy: "cloudy-day-2",
  mostly_clear: "cloudy-day-1",
  clear: "day",
};

export const cwcClimacellNightIcons: { [key: string]: string; } = {
  ...cwcClimacellDayIcons,
  freezing_rain_heavy: "rainy-6",
  freezing_rain: "rainy-5",
  freezing_rain_light: "rainy-4",
  // freezing_drizzle: "rain-and-sleet-mix",
  // ice_pellets_heavy: "rain-and-snow-mix",
  // ice_pellets: "rain-and-snow-mix",
  // ice_pellets_light: "rain-and-snow-mix",
  snow_heavy: "snowy-6",
  snow: "nowy-5",
  snow_light: "nowy-4",
  // flurries: "wind",
  // tstorm: "tropical-storm",
  rain_heavy: "rainy-6",
  rain_light: "rainy-4",
  rain: "rainy-5",
  drizzle: "rainy-4",
  // fog_light: "haze",
  // fog: "fog",
  // cloudy: "cloudy",
  mostly_cloudy: "cloudy-night-3",
  partly_cloudy: "cloudy-night-2",
  mostly_clear: "cloudy-night-1",
  clear: "day-night"
};
