//clear=ok, partlycloudy=ok, cloudy=ok, partlycloudy-fog=ok, partlycloudy-light-rain=ok, partlycloudy-rain=ok,
// light-rain=ok, rainy=ok, snowy-rainy=ok, partlycloudy-light-snow=ok, partlycloudy-snow=ok, light-snow=ok, snowy=ok,
// partlycloudy-lightning=ok or lightning

export const cwcBuienradarDayIcons: { [key: string]: string; } = {
  // freezing_rain_heavy: "rainy-3",
  // freezing_rain: "rainy-2",
  // freezing_rain_light: "rainy-1",
  // freezing_drizzle: "rain-and-sleet-mix",
  // ice_pellets_heavy: "rain-and-snow-mix",
  // ice_pellets: "rain-and-snow-mix",
  // ice_pellets_light: "rain-and-snow-mix",
  snowy: "snowy-3",
  "light-snow": "snowy-2",
  "snowy-rainy": "snowy-1",
  "partlycloudy-light-snow": "snowy-1",
  "partlycloudy-snow": "snowy-1",
  // flurries: "wind",
  // tstorm: "tropical-storm",
  // rain_heavy: "rainy-3",
  "partlycloudy-light-rain": "rainy-1",
  "light-rain": "rainy-1",
  "rainy": "rainy-2",
  "partlycloudy-rain": "rainy-1",
  // fog_light: "haze",
  "partlycloudy-fog": "fog",
  cloudy: "cloudy-original",
  // mostly_cloudy: "cloudy-day-3",
  partlycloudy: "cloudy-day-2",
  "partlycloudy-lightning": "cloudy-day-1",
  lightning: "cloudy-day-1",
  // mostly_clear: "cloudy-day-1",
  clear: "day",
};

export const cwcBuienradarNightIcons: { [key: string]: string; } = {
  ...cwcBuienradarDayIcons,
  // freezing_rain_heavy: "rainy-6",
  // freezing_rain: "rainy-5",
  // freezing_rain_light: "rainy-4",
  // freezing_drizzle: "rain-and-sleet-mix",
  // ice_pellets_heavy: "rain-and-snow-mix",
  // ice_pellets: "rain-and-snow-mix",
  // ice_pellets_light: "rain-and-snow-mix",
  // snow_heavy: "snowy-6",
  // snow: "nowy-5",
  // snow_light: "nowy-4",
  // flurries: "wind",
  // tstorm: "tropical-storm",
  // rain_heavy: "rainy-6",
  // rain_light: "rainy-4",
  // rain: "rainy-5",
  // drizzle: "rainy-4",
  // fog_light: "haze",
  // fog: "fog",
  // cloudy: "cloudy",
  // mostly_cloudy: "cloudy-night-3",
  // partly_cloudy: "cloudy-night-2",
  // mostly_clear: "cloudy-night-1",
  // clear: "night"
};